keycodes = [

        { "key": "esc",   "type": 1, "code": 1 },
        { "key": "space", "type": 1, "code": 57 },

        { "key": "alt",   "type": 1, "code": 56 },
        { "key": "shift", "type": 1, "code": 42 },
        { "key": "ctrl",  "type": 1, "code": 29 },
        { "key": "tab",   "type": 1, "code": 15 },

        { "key": "lmb",   "type": 3, "code": 1, },
        { "key": "rmb",   "type": 3, "code": 2, },
        { "key": "fmb",   "type": 1, "code": 4, },
        { "key": "bmb",   "type": 1, "code": 5, },

        { "key": "1",     "type": 1, "code": 2 },
        { "key": "2",     "type": 1, "code": 3 },
        { "key": "3",     "type": 1, "code": 4 },
        { "key": "4",     "type": 1, "code": 5 },
        { "key": "5",     "type": 1, "code": 6 },
        { "key": "6",     "type": 1, "code": 7 },
        { "key": "7",     "type": 1, "code": 8 },
        { "key": "8",     "type": 1, "code": 9 },
        { "key": "9",     "type": 1, "code": 10 },
        { "key": "0",     "type": 1, "code": 11 },

        { "key": "q",     "type": 1, "code": 16 },
        { "key": "w",     "type": 1, "code": 17 },
        { "key": "e",     "type": 1, "code": 18 },
        { "key": "r",     "type": 1, "code": 19 },
        { "key": "t",     "type": 1, "code": 20 },
        { "key": "y",     "type": 1, "code": 21 },
        { "key": "u",     "type": 1, "code": 22 },
        { "key": "i",     "type": 1, "code": 23 },
        { "key": "o",     "type": 1, "code": 24 },
        { "key": "p",     "type": 1, "code": 25 },

        { "key": "a",     "type": 1, "code": 30 },
        { "key": "s",     "type": 1, "code": 31 },
        { "key": "d",     "type": 1, "code": 32 },
        { "key": "f",     "type": 1, "code": 33 },
        { "key": "g",     "type": 1, "code": 34 },
        { "key": "h",     "type": 1, "code": 35 },
        { "key": "j",     "type": 1, "code": 36 },
        { "key": "k",     "type": 1, "code": 37 },
        { "key": "l",     "type": 1, "code": 38 },

        { "key": "z",     "type": 1, "code": 44 },
        { "key": "x",     "type": 1, "code": 45 },
        { "key": "c",     "type": 1, "code": 46 },
        { "key": "v",     "type": 1, "code": 47 },
        { "key": "b",     "type": 1, "code": 48 },
        { "key": "n",     "type": 1, "code": 49 },
        { "key": "m",     "type": 1, "code": 50 },

    ]
